server:
  port: 9998
##  tomcat:
 #   accesslog:
  #    directory: /Users/h-com/IdeaProjects/TIP
  #    enabled: true
   #   file-date-format: .yyyy-MM-dd
    #  prefix: access_log
     # suffix: .log


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tip?serverTimezone=UTC
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml




